BEGIN;
--
-- Create model Customer
--
CREATE TABLE "customers" ("customer_id" varchar(50) NOT NULL PRIMARY KEY, "customer_name" varchar(255) NOT NULL, "contact_email" varchar(254) NOT NULL, "phone_number" varchar(20) NOT NULL);
--
-- Create model Platform
--
CREATE TABLE "platforms" ("platform_id" uuid NOT NULL PRIMARY KEY, "platform_name" varchar(100) NOT NULL, "platform_config" jsonb NOT NULL);
--
-- Create model Order
--
CREATE TABLE "orders" ("order_id" varchar(50) NOT NULL PRIMARY KEY, "order_date" date NOT NULL, "platform_data" jsonb NULL, "customer_id" varchar(50) NOT NULL, "platform_id" uuid NOT NULL);
--
-- Create model Product
--
CREATE TABLE "products" ("product_id" varchar(50) NOT NULL PRIMARY KEY, "product_name" varchar(255) NOT NULL, "category" varchar(100) NOT NULL);
--
-- Create model OrderItem
--
CREATE TABLE "order_items" ("order_item_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity_sold" integer NOT NULL CHECK ("quantity_sold" >= 0), "selling_price" numeric(10, 2) NOT NULL, "total_sale_value" numeric(12, 2) NOT NULL, "order_id" varchar(50) NOT NULL, "product_id" varchar(50) NOT NULL);
--
-- Create model Delivery
--
CREATE TABLE "deliveries" ("delivery_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "delivery_address" varchar(255) NOT NULL, "delivery_date" date NOT NULL, "delivery_status" varchar(50) NOT NULL, "delivery_partner" varchar(100) NULL, "delivery_data" jsonb NULL, "order_id" varchar(50) NOT NULL UNIQUE);
--
-- Create index orders_order_d_6e39a9_idx on field(s) order_date of model order
--
CREATE INDEX "orders_order_d_6e39a9_idx" ON "orders" ("order_date");
--
-- Create index orders_platfor_474023_gin on field(s) platform_data of model order
--
CREATE INDEX "orders_platfor_474023_gin" ON "orders" USING gin ("platform_data");
--
-- Create index order_items_product_a53db1_idx on field(s) product of model orderitem
--
CREATE INDEX "order_items_product_a53db1_idx" ON "order_items" ("product_id");
--
-- Alter unique_together for orderitem (1 constraint(s))
--
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_product_id_selling_price_f7bbcf3e_uniq" UNIQUE ("order_id", "product_id", "selling_price");
CREATE INDEX "customers_customer_id_6b600f3d_like" ON "customers" ("customer_id" varchar_pattern_ops);
CREATE INDEX "platforms_platfor_0c264e_idx" ON "platforms" ("platform_name");
ALTER TABLE "orders" ADD CONSTRAINT "orders_customer_id_b7016332_fk_customers_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders" ADD CONSTRAINT "orders_platform_id_a1a14b41_fk_platforms_platform_id" FOREIGN KEY ("platform_id") REFERENCES "platforms" ("platform_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_order_id_5fe90b5c_like" ON "orders" ("order_id" varchar_pattern_ops);
CREATE INDEX "orders_customer_id_b7016332" ON "orders" ("customer_id");
CREATE INDEX "orders_customer_id_b7016332_like" ON "orders" ("customer_id" varchar_pattern_ops);
CREATE INDEX "orders_platform_id_a1a14b41" ON "orders" ("platform_id");
CREATE INDEX "products_product_id_eb399b28_like" ON "products" ("product_id" varchar_pattern_ops);
CREATE INDEX "products_categor_fce6e6_idx" ON "products" ("category");
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_412ad78b_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_dd557d5a_fk_products_product_id" FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "order_items_order_id_412ad78b" ON "order_items" ("order_id");
CREATE INDEX "order_items_order_id_412ad78b_like" ON "order_items" ("order_id" varchar_pattern_ops);
CREATE INDEX "order_items_product_id_dd557d5a" ON "order_items" ("product_id");
CREATE INDEX "order_items_product_id_dd557d5a_like" ON "order_items" ("product_id" varchar_pattern_ops);
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_order_id_delivery_status_d7da2b67_uniq" UNIQUE ("order_id", "delivery_status", "delivery_address");
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_order_id_26490c59_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "deliveries_order_id_26490c59_like" ON "deliveries" ("order_id" varchar_pattern_ops);
CREATE INDEX "deliveries_deliver_db2090_idx" ON "deliveries" ("delivery_status");
CREATE INDEX "deliveries_deliver_749590_gin" ON "deliveries" USING gin ("delivery_data");
COMMIT;
